version: "2"
services:
    worker:
        image: fogflow/worker
        volumes:
            - ./worker-config.json:/config.json
            - /var/run/docker.sock:/var/run/docker.sock

            
            
