version: "2"
services:
    edge_broker:
        image: fogflow/broker
        volumes:
            - ./broker-config.json:/config.json
    worker:
        image: fogflow/worker
        volumes:
            - ./worker-config.json:/config.json
            - /var/run/docker.sock:/var/run/docker.sock

            
            
